### ISSUE TITLE
macOS 10.11 Xcode8.2.1 can't get swift tests

### ISSUE THREAD

**Issue by Cyberbeni** [lyndsey-ferguson/xctest_list#4]
I've ran `nm -gU testAppUITests | cut -d' ' -f3 | xargs -s 131072 xcrun swift-demangle | cut -d' ' -f3 | grep -e '[\\.|_]'test` on this xcode 8.2.1 generated test binary on both macOS 10.11 Xcode 8.2.1 (xcrun version 31) and macOS 10.12 Xcode 9.2 (xcrun version 36) and they gave different results and the macOS 10.11 output didn't match this regex: 
https://github.com/lyndsey-ferguson/xctest_list/blob/master/lib/xctest_list.rb#L62
Built binary for reference: [testAppUITests.zip](https://github.com/lyndsey-ferguson/xctest_list/files/2773370/testAppUITests.zip)
macOS 10.11 output:

> testAppUITests.testAppUITests.testExample
testAppUITests.testAppUITests.setUp
testAppUITests.testAppUITests.tearDown
testAppUITests.testAppUITests.__allocating_init
testAppUITests.testAppUITests.__allocating_init
testAppUITests.testAppUITests.__allocating_init
testAppUITests.testAppUITests.__deallocating_deinit
testAppUITests.testAppUITests.init
testAppUITests.testAppUITests.init
testAppUITests.testAppUITests.init

macOS 10.12 output:

> testAppUITests.testAppUITests.testExample()
testAppUITests.testAppUITests.setUp()
testAppUITests.testAppUITests.tearDown()
testAppUITests.testAppUITests.__allocating_init(invocation:
testAppUITests.testAppUITests.__allocating_init(selector:
testAppUITests.testAppUITests.__allocating_init()
testAppUITests.testAppUITests.__deallocating_deinit
testAppUITests.testAppUITests.init(invocation:
testAppUITests.testAppUITests.init(selector:
testAppUITests.testAppUITests.init()

**Comment by Cyberbeni** [comment]
ah, can't copy from the 10.12 screen sharing for some reason, will have to fix the output manually in a minute

**Comment by lyndsey-ferguson** [comment]
Okay, here is what I think is going on.
1. I used to basically do this `nm -gU /Users/lyndsey.ferguson/Downloads/testAppUITests | xcrun swift-demangle | cut -d' ' -f3 | grep -E '.test[^.]+\(\)$'` to get the symbols. 
2. That stopped working with an Xcode upgrade and I had to use the new way of `nm`.

**Comment by Cyberbeni** [comment]
The output is the  same as on macOS 10.11 with Xcode 8.2.1

**Comment by lyndsey-ferguson** [comment]
Okay. I thought that `DEVELOPER_DIR=/Applications/Xcode8.2.1.app/Contents/Developer` prefixed to the command would do the same as `xcode-select -s`. It does not. I am reproducing the issue.

**Comment by lyndsey-ferguson** [comment]
@Cyberbeni I made some changes that may fix this. Can you follow [the instructions in the test_center](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/issues/86#issuecomment-460270295) Issue?

**Comment by lyndsey-ferguson** [comment]
Fixed in [v1.1.7](https://github.com/lyndsey-ferguson/xctest_list/releases/tag/v1.1.7)
