### ISSUE TITLE
Tests named "test" don't get discovered by xctest_list

### ISSUE THREAD

**Issue by scotthmccoy** [lyndsey-ferguson/xctest_list#6]
I was having a "No tests found" issue similar to this one: https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/issues/86

Example:
![image](https://user-images.githubusercontent.com/1480870/57415328-9d5fe100-71b0-11e9-80a2-51269fc45567.png)

However, while looking at the regex here https://github.com/lyndsey-ferguson/xctest_list/blob/master/lib/xctest_list.rb#L59 I noticed that tests that are simply named "test" would not get picked up.

However, all of my test methods *are* named "test"! I did this horrible thing to get around Xcode's limitation of 1 Simulator Clone per testcase class. I've organized all my test methods into their own separate classes:
![image](https://user-images.githubusercontent.com/1480870/57415425-faf42d80-71b0-11e9-8d99-a0b36177b533.png)

If I rename all my methods to "testGo", it's able to discover them all:

![image](https://user-images.githubusercontent.com/1480870/57415598-82da3780-71b1-11e9-9513-625d3f2d37b1.png)

**Comment by lyndsey-ferguson** [comment]
Whoops! Good find. I will fix it, and just to let you know, I am working on updating my other plugin to actually let you split all your tests among simulators to be run in parallel.

**Comment by lyndsey-ferguson** [comment]
Fixed in [v1.1.8](https://github.com/lyndsey-ferguson/xctest_list/releases/tag/v1.1.8)

**Comment by lyndsey-ferguson** [comment]
@scotthmccoy this will be released once `test_center` `3.8.0` is released. It shouldn't be long, I'm just waiting for confirmation on a simulator log collection crash that I fixed.
